POST http://localhost:8082/api/v1/employee/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTcwOTA2NDgsImV4cCI6MTcxNzE3NzA0OH0.05WhfBZtc2per6_7gH66h4mJ1CuqlBPTZcfWzusIG3o

{
  "firstName": "Tom",
  "lastName": "Cruise",
  "patronymic": "Disney",
  "age": 31,
  "passportSeries": "AA",
  "passportNumber": "00000003",
  "jshshir": "0000003",
  "nationality": "Dutch",
  "salary": 34000,
  "address": "NY",
  "departmentId": 2
}

###
GET http://localhost:8082/api/v1/employee/get/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTY2NTk2MzEsImV4cCI6MTcxNjc0NjAzMX0.9YpW6NY22UuZNnzzJ_0-EseXarMxr48VRxHYQlY0jXQ

###

GET http://localhost:8082/api/v1/employee/list?page=0&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTcwOTA2NDgsImV4cCI6MTcxNzE3NzA0OH0.05WhfBZtc2per6_7gH66h4mJ1CuqlBPTZcfWzusIG3o

###
PUT http://localhost:8082/api/v1/employee/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTY0NjM0ODcsImV4cCI6MTcxNjU0OTg4N30.FuTuT270m7aDElxhV8JEgxoEaO5FtmSK7Ey0VoqHhDg

{
  "firstName": "Tom",
  "lastName": "Hardy",
  "patronymic": "Chris",
  "age": 32,
  "passportSeries": "AA",
  "passportNumber": "00000001",
  "jshshir": "00000005",
  "nationality": "British",
  "salary": 56000,
  "address": "Cambridge",
  "departmentId": 2
}

###
DELETE http://localhost:8082/api/v1/employee/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTY0NjM0ODcsImV4cCI6MTcxNjU0OTg4N30.FuTuT270m7aDElxhV8JEgxoEaO5FtmSK7Ey0VoqHhDg




