POST http://localhost:8082/api/v1/expense/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTY3MTk2NzIsImV4cCI6MTcxNjgwNjA3Mn0.ZOOkEEG5AP1yJ6kCB8CNFIFVllw42OcX-lBBclUAPCE

{
  "adsType": "Instagram ads",
  "cost": 1200.43,
  "duration": 23,
  "employeeId": 2
}

###
GET http://localhost:8082/api/v1/expense/get/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTY3MTk2NzIsImV4cCI6MTcxNjgwNjA3Mn0.ZOOkEEG5AP1yJ6kCB8CNFIFVllw42OcX-lBBclUAPCE