POST http://localhost:8082/api/v1/user/sign-up
Content-Type: application/json

{
  "firstName": "jahongir",
  "lastName": "azimov",
  "email": "johangir0744@gmail.com",
  "password": "321",
  "role": "ADMIN"
}

###
POST http://localhost:8082/api/v1/user/sign-in
Content-Type: application/json

{
  "field": "jahongir@gmail.com",
  "object": "321"
}

###
GET http://localhost:8082/api/v1/user/get/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTcwOTA2NDgsImV4cCI6MTcxNzE3NzA0OH0.05WhfBZtc2per6_7gH66h4mJ1CuqlBPTZcfWzusIG3o

###
GET http://localhost:8082/api/v1/user/list?page=0&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2hhbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTcwOTA1MzksImV4cCI6MTcxNzE3NjkzOX0.2Hln8yMJe1UG6koHA6Bx111YUTIGzCkNe533Q7Y33UY

###
PUT http://localhost:8082/api/v1/user/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2hhbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTcwOTA1MzksImV4cCI6MTcxNzE3NjkzOX0.2Hln8yMJe1UG6koHA6Bx111YUTIGzCkNe533Q7Y33UY

{
  "firstName": "jahongir",
  "lastName": "azimov",
  "email": "jahongir@gmail.com",
  "password": "321",
  "role": "ADMIN"
}

###
DELETE http://localhost:8082/api/v1/user/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWhvbmdpckBnbWFpbC5jb20iLCJpYXQiOjE3MTY0NjM0ODcsImV4cCI6MTcxNjU0OTg4N30.FuTuT270m7aDElxhV8JEgxoEaO5FtmSK7Ey0VoqHhDg
